services:   
  db:     
    image: postgres:17-alpine
    container_name: postgres_db     
    environment:       
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:       
      - postgres_data:/var/lib/postgresql/data     
    ports:       
      - "5434:5432"
  backend:     
    build: ./backend
    # command: python manage.py runserver 0.0.0.0:8000     
    volumes:       
      - ./backend:/code   
    env_file:
      - .env      
    ports:       
      - "8000:8000"     
    depends_on:       
      - db
  frontend:     
    build: ./frontend
    volumes:
      # - .:/frontend
      # - ./node_modules:/frontend/node_modules
      - ./frontend:/code 
    ports:       
      # - "3000:5173" # для dev
      - "3000:80" # для prod

volumes:   
  postgres_data: